export {default as Navbar} from './Navbar/Navbar'
export {default as Banner} from './Banner/Banner'
export {default as Projects} from './Projects/Projects'
export {default as Contact} from './Contact/Contact'
export {default as Footer} from './Footer/Footer'
